server:
  port: 0
  
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:msdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      
  application:
    name: Services-Service  
 
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
   
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
pivotal:
  patientservice:
    name: Patient-Service
  servicesservice:
    name: Services-Service    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "ALWAYS" 
        
        
                  